### PR TITLE
✅ simplify the operation of adding new tests case based of file

### PR DESCRIPTION
**Pull request by coliss86**
Instead of creating a test case for each file to test, now we just have to put files in the corresponding file. 
The format is : 
- fileToTest.svg
- fileToTest_expected.txt

### CODE REVIEW

**Comment by PPAC37** [comment]
handy, thank you!

(if we delete the files (*.svg, *.sb3) ... the test will be a success?
 (possibly generate a list of files that must exist that we copy and paste into a kind of table of pre-required files? )

I think an autogenerator of _expected.txt if they don't exist would be handy as well.

**Comment by coliss86** [comment]
> (if we delete the files (*.svg, *.sb3) ... the test will be a success?

Yes

> (possibly generate a list of files that must exist that we copy and paste into a kind of table of pre-required files? )

I was thinking of this possibility too. As you noticed it, I will change it.

> I think an autogenerator of _expected.txt if they don't exist would be handy as well.

This an empty file, no need to "generate" it :)

**Comment by i-make-robots** [comment]
sounds good.  I'm learning a lot about unit testing from you :)

**Comment by coliss86** [comment]
@PPAC37 I modified the code. What do you think of it ?

**Comment by PPAC37** [comment]
It's great !
And as it goes through getRessource, "/" should remain compatible on windows. Perfect for me.

**Comment by coliss86** [comment]
`/` is correct because we are looking file in the classpath not on the file system. This is the job to convert it to the correct value based on the OS.

**Pull request merged**
