### PR TITLE
Fix for module info

### PR DESCRIPTION
**Pull request by i-make-robots**
does this work for everyone?

### CODE REVIEW

**Comment by PPAC37** [comment]
I get the same errors a the CI build 
`cannot access org.w3c.dom.css.ViewCSS
  class file for org.w3c.dom.css.ViewCSS not found
...
`
unless i add to pom.xml 
`
<dependency> 
    <groupId>xml-apis</groupId>
    <artifactId>xml-apis</artifactId>
    <version>1.4.01</version>
</dependency>
`
found after a goolge search in https://stackoverflow.com/questions/13840989/eclipse-java-lang-noclassdeffounderror-org-w3c-dom-elementtraversal

But i totally don't know what i ' m doing ... and if this is the good way ...

**Comment by i-make-robots** [comment]
That's the same dependency I had to *remove* in order to make things compile.

**Comment by i-make-robots** [comment]
```
		<!-- https://mvnrepository.com/artifact/org.apache.xmlgraphics/batik-xml -->
		<dependency>
		    <groupId>org.apache.xmlgraphics</groupId>
		    <artifactId>batik-all</artifactId>
		    <version>1.14</version>
			<exclusions>
	        	<exclusion>  <!-- declare the exclusion here -->
				    <groupId>xml-apis</groupId>
				    <artifactId>xml-apis</artifactId>
	        	</exclusion>
	      	</exclusions> 
		</dependency>
```

**Comment by i-make-robots** [comment]
didn't work for everyone.

**Pull request closed without merging**
