### PR TITLE
Reorder fix

### PR DESCRIPTION
**Pull request by Jip-Hop**
I merged the master branch into dev and fixed it from there.

### CODE REVIEW

**Comment by i-make-robots** [comment]
line 170: did you remove the bestD = d?  I'm not sure how it would keep the flipped line in sequence.

**Comment by i-make-robots** [comment]
omg, did I commit a non-release on the master branch?  *seppuku*

**Comment by i-make-robots** [comment]
I'm going to close this because I was dumb and committed to the master branch.  I have re-upped a commit to dev.

**Comment by Jip-Hop** [comment]
Can happen to the best of us! Haha. Hopefully this time we get it right.

**Pull request closed without merging**
