### PR TITLE
🔊 move log to user home and add dropdown menu to the log panel to select the log file to view

### PR DESCRIPTION
**Pull request by coliss86**
Here is the enhanced log panel: 
image

@PPAC37 @i-make-robots can you please test this feature? It should solved the problem that @PPAC37 found in the review of https://github.com/MarginallyClever/Makelangelo-software/pull/536#issuecomment-1037228202: 
> In fact this is a security issues. As my user have no admin right the path defined in the shortcut is not writable.

### CODE REVIEW

**Comment by PPAC37** [comment]
Ok for me (Ubuntu 18.04, run from NetBeans and from `java -jar ...` )
image

**Comment by coliss86** [comment]
> Ok for me (Ubuntu 18.04, run from NetBeans and from `java -jar ...` ) 

perfect, thanks !

**Comment by i-make-robots** [comment]
Does it cycle log files after 5 or 10?  users won't want to be confused with many log files.

**Comment by coliss86** [comment]
it keeps 1 old files. It is specified here: https://github.com/MarginallyClever/Makelangelo-software/blob/master/src/main/resources/logback.xml#L25

**Pull request merged**
