### PR TITLE
Moved java files to src/main/java and src/test/java 

### PR DESCRIPTION
**Pull request by coliss86**
the default maven structure is described [here](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html)

### CODE REVIEW

**Comment by PPAC37** [comment]
Thank you.

I am not familiar with Maven. This will be the place to learn more for me.

So in a practical way, any modifications not currently committed made on other forks (or in stash) will have to be readjusted because the file paths have changed ?

**Comment by coliss86** [comment]
> So in a practical way, any modifications not currently committed made on other forks (or in stash) will have to be readjusted because the file paths have changed ?

Yes, but if your PR #395 get merged before this one, you will not have to import those modifications in your branch.
For the next PR you may create, you'll have to fetch modification from upstream to your repo and you'll get those modifications.

**Comment by i-make-robots** [comment]
Conflicts that must be resolved.

**Comment by coliss86** [comment]
Conflicts are resolved

**Comment by i-make-robots** [comment]
Capture6
Seems to work.  I'd love to know why resources aren't where they belong in my Eclipse view...

**Comment by coliss86** [comment]
I do not remember how eclipse works, but you have 2 options:
- reimport the project in it
- add src/main/java as a source folder, same thing to src/test/java

**Pull request merged**
