### PR TITLE
Test to validate languages xml files have no duplicated key.

### PR DESCRIPTION
**Pull request by PPAC37**
This should allow a CI faild if found some duplicated key values in the language .xml files

And give this kind of output.
~~~
07:49:25.549 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:752  cvc-identity-constraint.4.1: Duplicate unique value [Left] declared for identity constraint "string_key_unique" of element "language".
07:49:25.553 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:757  cvc-identity-constraint.4.1: Duplicate unique value [Right] declared for identity constraint "string_key_unique" of element "language".
07:49:25.566 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:1007 cvc-identity-constraint.4.1: Duplicate unique value [MenuSaveFile] declared for identity constraint "string_key_unique" of element "language".
07:49:25.573 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:1140 cvc-identity-constraint.4.1: Duplicate unique value [spraypaintToolTest] declared for identity constraint "string_key_unique" of element "language".
07:49:25.583 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:1352 cvc-identity-constraint.4.1: Duplicate unique value [RobotMenu.GetTimeEstimate] declared for identity constraint "string_key_unique" of element "language".
07:49:25.590 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:1486 cvc-identity-constraint.4.1: Duplicate unique value [MenuResetMachinePreferences] declared for identity constraint "string_key_unique" of element "language".
07:49:25.590 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:1491 cvc-identity-constraint.4.1: Duplicate unique value [MenuLog] declared for identity constraint "string_key_unique" of element "language".
07:49:25.591 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:1497 cvc-identity-constraint.4.1: Duplicate unique value [PaperSize] declared for identity constraint "string_key_unique" of element "language".
07:49:25.607 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:1910 cvc-identity-constraint.4.1: Duplicate unique value [voronoiStipplingCellCount] declared for identity constraint "string_key_unique" of element "language".
07:49:25.607 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:1916 cvc-identity-constraint.4.1: Duplicate unique value [voronoiStipplingDotMin] declared for identity constraint "string_key_unique" of element "language".
07:49:25.612 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:2057 cvc-identity-constraint.4.1: Duplicate unique value [NotConnected] declared for identity constraint "string_key_unique" of element "language".
07:49:25.613 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:2075 cvc-identity-constraint.4.1: Duplicate unique value [FileTypeImage] declared for identity constraint "string_key_unique" of element "language".
07:49:25.614 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/english.xml:2087 cvc-identity-constraint.4.1: Duplicate unique value [Open] declared for identity constraint "string_key_unique" of element "language".
07:49:25.642 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/german.xml:603  cvc-identity-constraint.4.1: Duplicate unique value [Left] declared for identity constraint "string_key_unique" of element "language".
07:49:25.642 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/german.xml:608  cvc-identity-constraint.4.1: Duplicate unique value [Right] declared for identity constraint "string_key_unique" of element "language".
07:49:25.650 [main] INFO  com.marginallyclever.makelangelo.LanguagesXmlValidationForNoDupplicatedKey - [   error ] file:/home/q6/tmp_git_try/PPAC37/Makelangelo-software/src/main/resources/languages/german.xml:862  cvc-identity-constraint.4.1: Duplicate unique value [MenuSaveFile] declared for identity constraint "string_key_unique" of element "language".

~~~

### CODE REVIEW

**Comment by coliss86** [comment]
Nice one ! :)
You should create 2 tests files to test your test: one with xml errors and one with no error. Thus, you will be able to adjust your code without modifying original files of the app and the project will have confidence in those tests as they test themself.

Can you also correct the indentation of the code please ?

**Comment by PPAC37** [comment]
> You should create 2 tests files to test your test: one with xml errors and one with no error. Thus, you will be able to adjust your code without modifying original files of the app and the project will have confidence in those tests as they test themself.

Thank you. I hadn't thought of that, it's actually much better. 

> Can you also correct the indentation of the code please ?

normally it's done now. 

Juste to remove all duplicated key in
* [ ]  german.xml
* [ ] dutch.xml
* [ ] chinese.xml
* [ ] piglatin.xml ?

Normaly 
* [ ] english.xml is done but a native english speaker should check my corrections

**Comment by PPAC37** [comment]
english.xml

key:"Left"
* [ ] value"Left" 

key:"Right"
* [ ] value"Right" 

key:"MenuLog"
* [ ] value"Log" 

key:"PaperSize"
* [ ] value"Paper Size" 

key:"voronoiStipplingDotMin"
* [ ] value"Min dot size" 

key:"MenuSaveFile"
* [ ] value"Save"
* [ ] value"Save File..." 

key:"spraypaintToolTest"
* [ ] value"Make a dot"
* [ ] value"Spraypaint" 

key:"MenuResetMachinePreferences"
* [ ] value"Reset Preferences"
* [ ] value"Reset" 

key:"voronoiStipplingCellCount"
* [ ] value"Number of cells"
* [ ] value"Number of Cells" 

key:"NotConnected"
* [ ] value"Not connected"
* [ ] value"Not Connected" 

key:"FileTypeImage"
* [ ] value"Image"
* [ ] value"Image (jpg/bmp/png/gif)" 

key:"Open"
* [ ] value"Open file..."
* [ ] value"Open File dialog "

**Comment by i-make-robots** [comment]
Can we all agree to drop pig latin?  It was funny when I was first adding translations.  It is no longer required.

**Comment by PPAC37** [comment]
> Can we all agree to drop pig latin? It was funny when I was first adding translations. It is no longer required.

For me this is a yes. 
Deletion of piglatin.xml done in https://github.com/MarginallyClever/Makelangelo-software/pull/506/commits/2f0c18f52b18d3dc02c581f5bdab377c82398684

**Comment by PPAC37** [comment]
After that, I was thinking of adding two more tests (but in other PR)
check that the language files, other than english.xml:
- don't have keys that don't exist in english.xml.
- base on english.xml identify the missing keys. (To be able to request additional translations)

Of course this implies that using a new translation file in an old version of Makelangelo will cause problems of missing key, unsuitable translation. And so (thanks git ) it would be necessary to keep all the .xml files of a version/release.

**Comment by coliss86** [comment]
> Of course this implies that using a new translation file in an old version of Makelangelo will cause problems of missing key, unsuitable translation. And so (thanks git ) it would be necessary to keep all the .xml files of a version/release.

Don't worry, translation file are bundle in the jar, so whatever version you take, the corresponding translations are in.

**Comment by i-make-robots** [comment]
So... is this done?

**Comment by PPAC37** [comment]
> So... is this done?

If you checked my choices on the values retained for the duplicate keys in english.xml then yes, it seems to me finished. (Unless you have something to complain about the architecture such as not creating a class for the XML validation function in the sources (because there it is only available in the tests))

And unless @coliss86  has comments

**Comment by coliss86** [comment]
Yes: please fix the indentation, it miss 1 tab or 4 spaces in every method at least.
image

Don't you see it ?

**Comment by i-make-robots** [comment]
like @PPAC37 said

[ ] guarantee keys in language X exactly match keys in english.xml.  no extras.
[ ] guarantee keys in language X exactly match keys in english.xml.  no missing.

and I might add

[ ] generator that produces all keys and empty values?

I haven't checked which duplicates were retained.

"Image (jpg/bmp/png/gif)"  could be greater.  For example, PIO is missing.  The part in the () should be built from valid extensions OR no extensions shown.  

Everything else is tweakable later.

**Comment by PPAC37** [comment]
sorry that was it (couldn't see it. because i had set up 8 spaces as equivalence for a tab character and so it looked fine under my IDE and i don't know why but the diff view under github should be configured like this in My Settings.)
image

I'll fix that in a future PR. My excuses.

**Comment by i-make-robots** [comment]
Now when I pull & build I get `The package javax.xml.transform.stream is accessible from more than one module: <unnamed>, java.xml`

**Comment by i-make-robots** [comment]
ErrorHandler cannot be resolved to a type
SAXException cannot be resolved to a type
SAXException cannot be resolved to a type
SAXException cannot be resolved to a type
SAXException cannot be resolved to a type
SAXParseException cannot be resolved to a type
SAXParseException cannot be resolved to a type
SAXParseException cannot be resolved to a type
Schema cannot be resolved to a type
SchemaFactory cannot be resolved
SchemaFactory cannot be resolved to a type
Source cannot be resolved to a type
StreamSource cannot be resolved to a type
The package javax.xml.transform.stream is accessible from more than one module: <unnamed>, java.xml
The package javax.xml.transform is accessible from more than one module: <unnamed>, java.xml
The package javax.xml.validation is accessible from more than one module: <unnamed>, java.xml
The package javax.xml.validation is accessible from more than one module: <unnamed>, java.xml
The package javax.xml.validation is accessible from more than one module: <unnamed>, java.xml
The package javax.xml is accessible from more than one module: <unnamed>, java.xml
The package org.xml.sax is accessible from more than one module: <unnamed>, java.xml
The package org.xml.sax is accessible from more than one module: <unnamed>, java.xml
The package org.xml.sax is accessible from more than one module: <unnamed>, java.xml
Validator cannot be resolved to a type
XMLConstants cannot be resolved to a variable

**Comment by PPAC37** [comment]
I'm confused, I don't have this problem at home.
you seem to be missing a dependency or you have to add it in the depandace of the tests or a problem of definition in the module.java but I speak without knowing.

From what I understand SAX is provided by the JDK but there is a mechanism that replaces the "factories" when adding the lib xalan

So in summary test if by adding in the test dependencies
xml-apis
xalan
(they are normally already in the depandances but not yet in the test depandance)
and or
in module.java
requires xml.apis;
requires xalan;

if the problem changes or is resolved or do not change ...

**Comment by PPAC37** [comment]
Sorry have edited my previous message 
in module-info.xml adding 
requires xalan or xml-api are creating more errors.
but maybe 
 requires java.xml; 
is what you need ...

**Comment by coliss86** [comment]
please @i-make-robots @PPAC37 can you try to run the app without the file `module-info.java` ? I don't think it is required. On my setup, it is not. If the app can run without it, it should be removed. It's a JDK functionality to help (not to my mind) the distribution of java library and make sure other application cannot use some "private" package. But it creates more trouble than it solve.

**Comment by PPAC37** [comment]
As I don't really understand the use of module-info.java (which seems to be for jave 9) 
and don't know how to modify / add to it, 
and as it is marked as being in error in my Netbeans IDE, 

delete the file like the coliss86 propse doesn't bother me and will surely save us some problems.

And for the javadoc we will have the complete "package" in the index, which seems better to me...

**Comment by i-make-robots** [comment]
Removing it creates more module problems.  Since Java 9 it has been an issue for me.

**Comment by coliss86** [comment]
what issue do you have ? does the application still compiles ?

**Comment by i-make-robots** [comment]
It does not compile without module-info.java.  with module-info, 24 errors, 19 warnings.  Without, 112 errors, 12 warnings.
All the errors in both cases appear to be related to java.xml

**Comment by i-make-robots** [comment]
https://www.eclipse.org/forums/index.php/m/1849856/#msg_1849856

**Comment by PPAC37** [comment]
Seems like I owe @i-make-robots  an apology for having the terrible (considering the trouble) idea of using xml validation in testing.

**My apologies  @i-make-robots  for this hassle.**

**Pull request merged**
