### PR TITLE
Exit when all elements are stopped

### PR DESCRIPTION
**Pull request by coliss86**
when clicking on exit in the "file" menu, the JVM does not exit. Here is a fix.

### CODE REVIEW

**Comment by i-make-robots** [comment]
I'm pretty sure the JFrame closing is supposed to kill the thread and so system.exit() is not supposed to be called.

**Comment by i-make-robots** [comment]
on my system `File > Quit` works fine, no lingering thread.

**Comment by PPAC37** [comment]
For me, the JFrame close on File -> Quit. 
But if i run the jar via a command line, i dont get back the prompt ... the JVM is still running ... 
```
6@q6-pc:~/Downloads$ java -jar makelangelo-nightly-20211220-a83707.jar
log dir=/home/q6/Downloads/

```
i need to do do ctrl+c get back the promt ...
```
q6@q6-pc:~/Downloads$ java -jar makelangelo-nightly-20211220-a83707.jar
log dir=/home/q6/Downloads/
^Cq6@q6-pc:~/Downloads$ 
```

**Comment by coliss86** [comment]
hum weird :-(
When launching from a console or with IntelliJ, it does not exit, the window is still closed.

**Comment by i-make-robots** [comment]
Then something more serious is happening. The h frame is not drawing but has not completely closed?

**Comment by coliss86** [comment]
yes, nothing is visible

**Comment by coliss86** [comment]
do you want to investigate more or as the application is closing, this call is enough ?

**Comment by coliss86** [comment]
I get the same behaviour when launching `ScaleTurtlePanel.main()`: the window close but the jvm remains up...

**Comment by i-make-robots** [comment]
mainFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); is the default behavior.
mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); is set during mainFrame.windowClosing() --> onClose().
mainFrame.windowClosed() comes after that and should correctly exit.

FWIW, there's also https://tips4java.wordpress.com/2009/05/01/closing-an-application/ which makes a nice ExitAction.  still doesn't explain why the process fails to quit for some people.

**Pull request closed without merging**
