### PR TITLE
Firmware upload rework ( to consider as a draft )

### PR DESCRIPTION
**Pull request by PPAC37**
Firmware update rework.
for evaluation / discussion.

I take note of all the comments made in https://github.com/MarginallyClever/Makelangelo-software/pull/405 
( My apologies if I do not correct this immediately. (I take advantage of the holiday season with the family.) )

And maybe i should wait for PR https://github.com/MarginallyClever/Makelangelo-software/pull/402  to be finish and  merged.

Good continuation, and happy holidays.

### CODE REVIEW

**Comment by i-make-robots** [comment]
I cannot pull and test draft PRs.

**Comment by PPAC37** [comment]
Still have to take into account some coliss86's remarks from https://github.com/MarginallyClever/Makelangelo-software/pull/405. (code formatting, using logger. * Instead of Systeme.out.print *, ...) 
The next commit should have taken this into account.

**Comment by PPAC37** [comment]
> I cannot pull and test draft PRs.

Hello

Normally there is a possibility to do that
https://stackoverflow.com/questions/9153598/how-do-i-fetch-a-branch-on-someone-elses-fork-on-github

But since it's not necessarily the most practical ... I get out of "draft" mode.
But be careful, it's still to rework / review / discuss!

**Comment by i-make-robots** [comment]
log dir=C:\Users\aggra\Documents\GitHub\makelangelo-software\
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.JButton.setForeground(java.awt.Color)" because "this.button" is null
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.select.SelectButton.setForeground(SelectButton.java:50)
	at java.desktop/javax.swing.LookAndFeel.installColors(LookAndFeel.java:181)
	at java.desktop/javax.swing.LookAndFeel.installColorsAndFont(LookAndFeel.java:212)
	at java.desktop/javax.swing.plaf.basic.BasicPanelUI.installDefaults(BasicPanelUI.java:77)
	at java.desktop/javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:62)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:95)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.select.Select.<init>(Select.java:21)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.select.SelectButton.<init>(SelectButton.java:27)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.firmwareUploader.FirmwareUploaderPanel.<init>(FirmwareUploaderPanel.java:36)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.Makelangelo.runFirmwareUpdate(Makelangelo.java:493)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.Makelangelo.lambda$19(Makelangelo.java:436)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1012)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1056)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by i-make-robots** [comment]
Capture10

**Comment by PPAC37** [comment]
> resize window make avrdude log very very long. Use a JScrollPane? Why does it get longer?

Totally agree, I am focusing for the moment on the functional need, the cosmetic of the interface was for later. (But there is some strange thing with the SelectTextArea event in a JScrollPane  (see a resize of the text generator)

**Comment by coliss86** [comment]
have a look at the `LogPanel` to get the idea of a scrollpane + textarea with a button

**Comment by PPAC37** [comment]
> have a look at the `LogPanel` to get the idea of a scrollpane + textarea with a button

Thank you.
In fact, it is a SelectTextArea in a SelectPanel which seems to be difficult to use correctly (something escapes me on their use ...).
I'm going to go back to a Simple JTextArea + JScrollPane ...

But strange the basic blocks (Select* class) are not more practical or better explained in their uses.

**Comment by PPAC37** [comment]
should we add an acceptance checkbox with this kind of message?

Warning: using a binary file that is not suitable for your machine could make it unusable. Please accept the risks beyond our responsibility and choose your file carefully.

or is there already a disclaimer included in the license used?

(because I just realized that I hadn't checked the user's input well,  and that if he had typed "format C: / Y" it could have been executed very well... (Oups sorry !)
And so I wonder about the responsibilities ...)

**Comment by i-make-robots** [comment]
I am out of touch.  is this still a draft?  is it moving forward?

**Comment by PPAC37** [comment]
Still a draft. Sorry I'm taking my time ...

**Comment by coliss86** [comment]
@PPAC37 you can edit the description of this PR to create a list of what should still be done and thus you can cleanup you code with those comments. When you have done an item, you'll be able to click on it to check it. It is great for the maintainer to see what you think is left on this PR. You can also edit, add or remove it at any time.
you can use `  - [ ] my item` and it will be rendered as follow:

  - [ ] my item

I use it for big PR to remind me what I have to do.

**Comment by coliss86** [comment]
Here is the doc for the task list: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

**Comment by PPAC37** [comment]
@coliss86  Thanks for the task list tips ! (I need to use this as i m adding to much TODOs in code and in the end I don't take the time to adjust / prioritize / put them together when it affects several parts of code. )
Also I need to find a little guide to properly name my commits. ( 
- [ ] Some String to set as traduction
- [ ] Some Traductions Key to normalize 
- [ ] Test implementation Process Exec
- [ ] Comments / Javadoc cleanning / review.
- [ ] generic Process Exec (to be maybe use in other contexte)
- [ ] Test implementation Process Exec
- [ ] Comments / Javadoc cleanning / review.
- [ ] ... some more will commes ;)

**Comment by i-make-robots** [comment]
If this is still a draft please mark it as draft.  If it is done then update the title.  Either way let me know.  Thank you!

**Pull request closed without merging**
