### PR TITLE
♻️ adjust lock as described in the javadoc

### PR DESCRIPTION
**Pull request by coliss86**

### CODE REVIEW

**Comment by i-make-robots** [comment]
Not sure how this makes any functional difference.  locks before, locks after exception is handled.  please demonstrate how it can fail.

**Comment by coliss86** [comment]
The log can fail after the log has been acquired and then it will be never released. It is implemented in the same way as https://github.com/MarginallyClever/Makelangelo-software/blob/master/src/main/java/com/marginallyclever/makelangelo/turtle/turtleRenderer/TurtleRenderFacade.java#L24

**Comment by coliss86** [comment]
Ho, I see the contrary in the javadoc: https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantLock.html, I'll update the other class

**Comment by i-make-robots** [comment]
good catch.  Javadoc ftw.  As it is written in scripture by the coders of old!

**Pull request merged**
