### PR TITLE
Add mvnw and update CI

### LINKED ISSUE #331: use maven wrapper to ease first build
**Is your feature request related to a problem? Please describe.**
In the README, it is stated that eclipse should be used to import the project in order to build it.
It could be easier to use maven to build it directly. Moreover, the [maven wrapper](https://github.com/takari/maven-wrapper) could be added to the project. I see that is there are some file of a previous installation in the `java/maven/wrapper`.

**Describe the solution you'd like**
If you want, I can add it and cleanup old files

**Describe alternatives you've considered**
none

### PR DESCRIPTION
**Pull request by coliss86**
Hi,

I have added mvnw to the project in order to be able to build it and run it without eclipse for the first time. I also cleanup old files from a previous installation of mvnw and update the README accordingly.

Fix #331 

Next time you update the minimum required version of maven, make sure to also update the file `.mvn/wrapper/maven-wrapper.properties`.

Could you please make sure the wording in the README is OK.

I also updated the CI : 
- the mvn job run on every branch
- upload of nightly build has been updated : 1.1.0 in order to get a fix which do not delete newest upload (cf https://github.com/WebFreak001/deploy-nightly/releases/tag/v1.1.0)
- upload nightly run only on the master branch

Can you also make sure to squash all my commit when it will be merged please ?

### CODE REVIEW

**Comment by i-make-robots** [comment]
please let me know when this is ready to test.

**Comment by coliss86** [comment]
It is ready

**Comment by i-make-robots** [comment]
ok, dumb question: how do i test this?  clean install on a non-eclipse system? :T

**Comment by coliss86** [comment]
Yes, eclipse is not needed to compile the software. Have a look at the README, I have provided the instructions to do so.

**Comment by i-make-robots** [comment]
I don't know what to do to validate this.

**Comment by coliss86** [comment]
To validate this PR, you can do the following: 
* Open a terminal emulator (`cmd` on Windows, `Terminal` on macOS or GNU/Linux) in the extracted folder.
* Build the application with `mvnw` (the first time, it downloads a lot of files):
  * `./mvnw clean install` on macOS or GNU/Linux
  * `mvnw.cmd clean install` on Windows
* in the `target/` folder, you will filnd the jar file with a name like : `Makelangelo*-with-dependencies.jar`

This is the jar used to launch the application.
This procedure is useful to automate the construction of the release.

**Comment by i-make-robots** [comment]
testing this now...

**Comment by i-make-robots** [comment]
Ran without error.

**Pull request merged**
