### PR TITLE
🐛 Fix #489: set the inner component's size with bounds

### LINKED ISSUE #489: Plotter Controls > Advanced Controls render outside parent bounding limits
**Steps to make the bug happen**
1. Load any image or vector
2. Open plotter controls
3. expand advanced controls

**What was supposed to happen**
tabs inside advanced control are now hanging off the edge of the window and cannot be seen.  "DRAW_LINE" in program window appears as "RAW_LINE".

**Platform (please complete the following information):**
 - Version: 7.31.x
 - Windows

**Additional context**
Also I see the plotter controls are called "robot controls" and so is the jog panel!  Two things with different jobs and the same name?!

### PR DESCRIPTION
**Pull request by coliss86**

### CODE REVIEW

**Comment by i-make-robots** [comment]
1. run app
2. makelangelo > open controls
3. expand advanced controls
```
 java.lang.NullPointerException: Cannot read field "width" because "this.initialDimension" is null
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.CollapsiblePanel.toggleVisibility(CollapsiblePanel.java:157)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.CollapsiblePanel.toggleVisibility(CollapsiblePanel.java:144)
	at com.marginallyclever.makelangelo/com.marginallyclever.makelangelo.CollapsiblePanel$1.mouseClicked(CollapsiblePanel.java:50)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4557)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by coliss86** [comment]
Strange, make sure you compiled the project, this PR does not change this part of the code.
Does the problem also occurs on master ?

**Comment by i-make-robots** [comment]
I confirm it does NOT happen on master.

**Comment by PPAC37** [comment]
(tested with a local fork of  https://github.com/coliss86/Makelangelo-software/tree/fix-resize ) and no exception for me ... (just the tabs that "jump a little" when clicked...)

**Comment by coliss86** [comment]
> (just the tabs that "jump a little" when clicked...)

Can you show me or explains better please ?

**Comment by coliss86** [comment]
@i-make-robots I push a fix, I assume the events generated by swing are not in the same order between macos/linux and windows

**Comment by i-make-robots** [comment]
Still happening.  I believe the correct fix is to repair the tabs and their contents, not the CollapsiblePanel.

**Comment by coliss86** [comment]
The NullPointerException exception is still happening ?
Can you make a screenshot of your IDE please with the git revision displayed somewhere please ?

**Comment by i-make-robots** [comment]
And just like that the exception is gone!  I don't understand.... I did a refresh and a Maven > update to make sure I was using the latest on 491...

**Comment by i-make-robots** [comment]
But now the behavior is even more strange.  hangs of the right side only and "flickers" while the panel is being resized.  flicker occurs when resizing vertically and horizontally.
d1

**Comment by coliss86** [comment]
After 3 hours to try / test, it is far better and no more flickering.
Can you confirm @i-make-robots  please ?

**Comment by i-make-robots** [comment]
Works here.  I love the +/- instead of the arrows.  much more intuitive.

**Pull request merged**
