### PR TITLE
👷 create the release package in the CI

### PR DESCRIPTION
**Pull request by coliss86**
As today, the CI produce a jar file, this will go one step further by generating a pre-release every time.
Moreover, today, it seems that the file that I put in the package folder where not in git and thus they cannot be maintained and only lived on dan computer.
Besides, as the CI will produce the zip every time, you will not have to remember where to get the files from and how to create the final release: just download the latest nightly and put it in the release of github.

### CODE REVIEW

**Comment by PPAC37** [comment]
Love it !
you certainely have to do a 
`sudo apt-get -y install zip`
before the zip command (or in set up environnement)  to have it available

**Comment by coliss86** [comment]
almost :) but it is a windows... so no apt-get :'(

**Comment by i-make-robots** [comment]
what is the motivation for this CI?  It will generate new releases all the time and that is good because...?

**Comment by coliss86** [comment]
You are correct: as today, the CI produce a jar file, this will go one step further by generating a pre-release every time.
Moreover, today, it seems that the file that I put in the package folder where not in git and thus they cannot be maintained and only lived on your computer.
Besides, as the CI will produce the zip every time, you will not have to remember where to get the files from and how to create the final release: just download the latest nightly and put it in the release of github.

I still have to find a proper way to produce a zip file on windows, it is a matter of few try / errors.

**Comment by PPAC37** [comment]
Windows server 2022 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
have 7zip 21.07 

`7z a -tzip Makelangelo.zip .`

**Comment by i-make-robots** [comment]
I am fine with this.  I don't want to be the bottleneck in any project.

**Comment by coliss86** [comment]
> Windows server 2022 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md have 7zip 21.07
> 
> `7z a -tzip Makelangelo.zip .`
> 
> Edit : or `7z a -tzip -bb1 Makelangelo.zip .` if you whant a verbose mode level 1 (what file have been added / updated /...)

Waou nice, tahnks ! I didn't know where to find this documentation
The CI is running `windows-latest`, it is `windows-2019`, 7zip is also available.

**Comment by coliss86** [comment]
I tested the zip produced, it looks the same as the one in the 7.31.0 release. When this PR will squashed and merged, I'll have a look of the nightly build to make sure it is ok as I can't test this latest part of the pipeline on my fork.

**Pull request merged**
