### PR TITLE
🐛 Truncate the history window to 500 lines in order to avoid fast scrolling of long history

### PR DESCRIPTION
**Pull request by coliss86**
Still some tests to do to invalidated or not the slowdown of the robot

### CODE REVIEW

**Comment by i-make-robots** [comment]
A test would have to fire 10k lines at the history dialog as though they were `NetworkSessionEvent` and then test to see if response time drops.  Interesting challenge...

**Comment by coliss86** [comment]
I have a bug : 
image

I have to investigate more

**Comment by coliss86** [comment]
Some more logs: 
```
2022-01-26 12:32:56,219 TRACE c.m.m.p.p.MarlinInterface - sending 'N314 G1 X50.921 Y89.088 F3000.0*90' 
2022-01-26 12:32:56,258 TRACE c.m.m.p.p.MarlinInterface - received 'ok' 
2022-01-26 12:32:56,258 TRACE c.m.m.p.p.MarlinInterface - sending 'N315 G1 X51.386 Y88.965 F3000.0*86' 
2022-01-26 12:32:56,267 TRACE c.m.m.p.p.MarlinInterface - received 'ok' 
2022-01-26 12:32:56,267 TRACE c.m.m.p.p.MarlinInterface - sending 'N316 G1 X52.261 Y88.524 F3000.0*87' 
2022-01-26 12:32:56,320 TRACE c.m.m.p.p.MarlinInterface - received 'ok' 
2022-01-26 12:32:56,322 TRACE c.m.m.p.p.MarlinInterface - sending 'N317 G1 X51.634 Y88.416 F3000.0*81' 
2022-01-26 12:32:57,244 TRACE c.m.m.p.p.MarlinInterface - received 'ok' 
2022-01-26 12:32:57,245 TRACE c.m.m.p.p.MarlinInterface - sending 'N318 G1 X51.016 Y88.250 F3000.0*92' 
2022-01-26 12:32:57,246 TRACE c.m.m.p.p.MarlinInterface - received 'ok' 
2022-01-26 12:32:57,246 TRACE c.m.m.p.p.MarlinInterface - sending 'N319 G1 X50.006 Y87.833 F3000.0*93' 
2022-01-26 12:32:58,168 TRACE c.m.m.p.p.MarlinInterface - received 'ok' 
2022-01-26 12:32:58,168 TRACE c.m.m.p.p.MarlinInterface - sending 'N320 G1 X48.856 Y87.204 F3000.0*93' 
2022-01-26 12:32:58,169 TRACE c.m.m.p.p.MarlinInterface - received 'Error:checksum mismatch, Last Line: 315' 
2022-01-26 12:32:58,169 ERROR c.m.m.p.p.MarlinInterface - Error from printer 'Error:checksum mismatch, Last Line: 315' 
```

**Comment by coliss86** [comment]
Here is small debug session with jconsole to have a look at the memory consumption: I loaded a big fractal drawing with the `master` version, it produces 110k lines of gcode from 17h10 to 17h55, the robot is drawing fast. At 17h55, I opned the marlin tab and the robot sloooowwwww dooown.

image

Thoses graphics show few things: memory, cpu and threads.

image

before 17h55, the memory is growing slowly but as soon as I opened the marlin tab, the cpu jumped (forget the Y axis on the CPU, it's wrong) and so the memory.

Now, I have to do the same with the optimization of this PR

**Comment by coliss86** [comment]
I get very good results with this new implementation: the queue is removed and old entries are cleared.

**Comment by i-make-robots** [comment]
Have you tried PR #486 ?

**Comment by coliss86** [comment]
not yet, I'll do it tomorrow

**Pull request closed without merging**
