### PR TITLE
🚚 convert all src folders to lowercase

### PR DESCRIPTION
**Pull request by coliss86**
Finished the renaming started in https://github.com/MarginallyClever/Makelangelo-software/pull/615

### CODE REVIEW

**Comment by PPAC37** [comment]
Thank you. (I dragged my feet to do it)
I didn't know if this is also to be done in NodeGraphCore or not...

**Comment by coliss86** [comment]
> Thank you. (I dragged my feet to do it) I didn't know if this is also to be done in NodeGraphCore or not...

I think so, the CI isn't working :'( There is something wrong with a mix of lower / camelcase in folder name.

The [java naming convention](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html) states: 
> The prefix of a unique package name is always written in all-lowercase ASCII letters and should be one of the top-level domain names, currently com, edu, gov, mil, net, org, or one of the English two-letter codes identifying countries as specified in ISO Standard 3166, 1981.

@i-make-robots can you please convert all the folder name of NodeGraphCore to lowercase please ?

**Comment by i-make-robots** [comment]
I'll submit a PR for gnc when I have it ready.  https://github.com/MarginallyClever/NodeGraphCore/issues/4

**Comment by i-make-robots** [comment]
https://github.com/MarginallyClever/NodeGraphCore/compare/lower-case-path-names?expand=1

**Comment by i-make-robots** [comment]
> com.marginallyclever.donatello => com.marginallyclever.donatelloimpl
doh!

**Comment by coliss86** [comment]
> > com.marginallyclever.donatello => com.marginallyclever.donatelloimpl
> > doh!

Yes :-(  see discord why

**Comment by coliss86** [comment]
@i-make-robots ready for review !

**Comment by PPAC37** [comment]
Under netbeans, Build ok but when running 
~~~
cd /home/q6/tmp_git_try/PPAC37/Makelangelo-software; DEV=true JAVA_HOME=/usr/lib/jvm/jdk-17 /home/q6/tmp_git_try/PPAC37/Makelangelo-software/mvnw -Dexec.vmArgs=-Denv.DEV=true "-Dexec.args=${exec.vmArgs} -classpath %classpath ${exec.mainClass} ${exec.appArgs}" -Dexec.appArgs=-nolf -Dexec.mainClass=com.marginallyclever.makelangelo.Makelangelo -Dexec.executable=/usr/lib/jvm/jdk-17/bin/java -Denv.DEV=true -DskipTests=true --update-snapshots -U org.codehaus.mojo:exec-maven-plugin:3.0.0:exec
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...

------------------< com.marginallyclever:Makelangelo >------------------
Building Makelangelo 7.32.0
--------------------------------[ jar ]---------------------------------

--- exec-maven-plugin:3.0.0:exec (default-cli) @ Makelangelo ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
~~~
so no logs ... ;-(

**Review by i-make-robots — APPROVED** [review]
wonderful!

**Pull request merged**
