### PR TITLE
More resilient LoadScratch3 with some fix (orientation)

### PR DESCRIPTION
**Pull request by PPAC37**
* [x] see https://github.com/MarginallyClever/Makelangelo-software/issues/534#issuecomment-1037317682
* [ ] In some case the Turtle setColor trouble the render result ... have to investigate ... Edit : ResizeTurtleToPaperAction resize = new ResizeTurtleToPaperAction(myPaper,false,""); seem to have trouble with colorChange in some case... cause if commented no issues until manualy activate it ...
* [x] hack loop forever allowed but iterated only once.
* [x] No error on loading a not clean Scratch project ( a variable block left in a script ...)
* [x] can render multiple block opcode event_whenflagclicked

### CODE REVIEW

**Comment by PPAC37** [comment]
> probably in doStart() the Turtle should be set to -90. that way if the first comand is "go forward" it moves in the correct direction.

it seems that at the initialization of a project the orientation is at 90° under scratch 
https://scratch.mit.edu/projects/645552141
(therefore should be at 0° in turtle doStart() ).

(but not if you do several times the green flag ... there it starts again on the value at the end of the previous exec ... it must be a technique to make you think about doing an initialization phase in your project scratch ... like adding a Go to (x=0, y=0) ...

**Comment by i-make-robots** [comment]
on green flag should not happen more than once in any script.  I believe the Scratch app won't let you have more than one green flag.

**Comment by PPAC37** [comment]
I expressed myself badly, I was talking about clicking several times on the green flag under scratch.
But your remark made me do a test. 
And unfortunately for us, it seems possible to have several times the "when green flag clicked" in the same script.

https://scratch.mit.edu/projects/645649727
image

**Comment by i-make-robots** [comment]
You're right.  Each one would run separately, not in parallel.  We can't wipe the Turtle to nothing on green flag.

**Comment by i-make-robots** [comment]
that suggests the problem is in resize, not in LoadScratch3

**Comment by PPAC37** [comment]
I think I found and solved my rendering bug story for some color changes in a Scratch3 project.

**Comment by i-make-robots** [comment]
I think your Turtle fix is correct.

**Pull request merged**
